version: '3'
services:
  flask:
     build: .
     image: fl_server_api:v1
     ports:
       - "5000:5000"
     volumes:
       - "./app:/usr/local/FL_API/app/"
       - "./scripts:/usr/local/FL_API/scripts/"
      #  - "./errors.log:/usr/local/FL_API/errors.log"
      #  - "./info.log:/usr/local/FL_API/info.log"
      #  - "./debug.log:/usr/local/FL_API/debug.log"
     restart: always
     container_name: fl_server_api_v1